vich_uploader:
    metadata:
        type: attribute
    db_driver: orm
    mappings:
        media:
            uri_prefix: /upload/media
            upload_destination: '%kernel.project_dir%/public/upload/media'
            delete_on_remove: true
            delete_on_update: true